' ----------------------------------------------------------------------------------
' Microsoft Developer & Platform Evangelism
' 
' Copyright (c) Microsoft Corporation. All rights reserved.
' 
' THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, 
' EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES 
' OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
' ----------------------------------------------------------------------------------
' The example companies, organizations, products, domain names,
' e-mail addresses, logos, people, places, and events depicted
' herein are fictitious.  No association with any real company,
' organization, product, domain name, email address, logo, person,
' places, or events is intended or should be inferred.
' ----------------------------------------------------------------------------------

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.208
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace SubmitApp
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="SubmitJobApplicationRequest", [Namespace]:="http://contoso.com/contracts/hr"),  _
     System.SerializableAttribute()>  _
    Partial Public Class SubmitJobApplicationRequest
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private RequestIDField As System.Guid
        
        Private ResumeField As SubmitApp.ApplicantResume
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property RequestID() As System.Guid
            Get
                Return Me.RequestIDField
            End Get
            Set
                If (Me.RequestIDField.Equals(value) <> true) Then
                    Me.RequestIDField = value
                    Me.RaisePropertyChanged("RequestID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property [Resume]() As SubmitApp.ApplicantResume
            Get
                Return Me.ResumeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ResumeField, value) <> true) Then
                    Me.ResumeField = value
                    Me.RaisePropertyChanged("Resume")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ApplicantResume", [Namespace]:="http://contoso.com/contracts/hr"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ApplicantResume
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private EducationField As String
        
        Private EmailField As String
        
        Private NameField As String
        
        Private NumReferencesField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property Education() As String
            Get
                Return Me.EducationField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EducationField, value) <> true) Then
                    Me.EducationField = value
                    Me.RaisePropertyChanged("Education")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property Email() As String
            Get
                Return Me.EmailField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EmailField, value) <> true) Then
                    Me.EmailField = value
                    Me.RaisePropertyChanged("Email")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property Name() As String
            Get
                Return Me.NameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NameField, value) <> true) Then
                    Me.NameField = value
                    Me.RaisePropertyChanged("Name")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property NumReferences() As Integer
            Get
                Return Me.NumReferencesField
            End Get
            Set
                If (Me.NumReferencesField.Equals(value) <> true) Then
                    Me.NumReferencesField = value
                    Me.RaisePropertyChanged("NumReferences")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="SubmitJobApplicationResponse", [Namespace]:="http://contoso.com/contracts/hr"),  _
     System.SerializableAttribute()>  _
    Partial Public Class SubmitJobApplicationResponse
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private ApplicantNameField As String
        
        Private ApplicationIDField As Integer
        
        Private ResponseTextField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property ApplicantName() As String
            Get
                Return Me.ApplicantNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ApplicantNameField, value) <> true) Then
                    Me.ApplicantNameField = value
                    Me.RaisePropertyChanged("ApplicantName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property ApplicationID() As Integer
            Get
                Return Me.ApplicationIDField
            End Get
            Set
                If (Me.ApplicationIDField.Equals(value) <> true) Then
                    Me.ApplicationIDField = value
                    Me.RaisePropertyChanged("ApplicationID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property ResponseText() As String
            Get
                Return Me.ResponseTextField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ResponseTextField, value) <> true) Then
                    Me.ResponseTextField = value
                    Me.RaisePropertyChanged("ResponseText")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://contoso.com/hr/", ConfigurationName:="SubmitApp.IApplicationService")>  _
    Public Interface IApplicationService
        
        'CODEGEN: Generating message contract since the operation SubmitJobApplication is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="http://contoso.com/hr/IApplicationService/SubmitJobApplication", ReplyAction:="http://contoso.com/hr/IApplicationService/SubmitJobApplicationResponse")>  _
        Function SubmitJobApplication(ByVal request As SubmitApp.SubmitJobApplicationRequest1) As SubmitApp.SubmitJobApplicationResponse1
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://contoso.com/hr/IApplicationService/SubmitJobApplication", ReplyAction:="http://contoso.com/hr/IApplicationService/SubmitJobApplicationResponse")>  _
        Function BeginSubmitJobApplication(ByVal request As SubmitApp.SubmitJobApplicationRequest1, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndSubmitJobApplication(ByVal result As System.IAsyncResult) As SubmitApp.SubmitJobApplicationResponse1
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class SubmitJobApplicationRequest1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://contoso.com/contracts/hr", Order:=0)>  _
        Public SubmitJobApplicationRequest As SubmitApp.SubmitJobApplicationRequest
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal SubmitJobApplicationRequest As SubmitApp.SubmitJobApplicationRequest)
            MyBase.New
            Me.SubmitJobApplicationRequest = SubmitJobApplicationRequest
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class SubmitJobApplicationResponse1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://contoso.com/contracts/hr", Order:=0)>  _
        Public SubmitJobApplicationResponse As SubmitApp.SubmitJobApplicationResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal SubmitJobApplicationResponse As SubmitApp.SubmitJobApplicationResponse)
            MyBase.New
            Me.SubmitJobApplicationResponse = SubmitJobApplicationResponse
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IApplicationServiceChannel
        Inherits SubmitApp.IApplicationService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class SubmitJobApplicationCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As SubmitApp.SubmitJobApplicationResponse
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),SubmitApp.SubmitJobApplicationResponse)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ApplicationServiceClient
        Inherits System.ServiceModel.ClientBase(Of SubmitApp.IApplicationService)
        Implements SubmitApp.IApplicationService
        
        Private onBeginSubmitJobApplicationDelegate As BeginOperationDelegate
        
        Private onEndSubmitJobApplicationDelegate As EndOperationDelegate
        
        Private onSubmitJobApplicationCompletedDelegate As System.Threading.SendOrPostCallback
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Event SubmitJobApplicationCompleted As System.EventHandler(Of SubmitJobApplicationCompletedEventArgs)
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SubmitApp_IApplicationService_SubmitJobApplication(ByVal request As SubmitApp.SubmitJobApplicationRequest1) As SubmitApp.SubmitJobApplicationResponse1 Implements SubmitApp.IApplicationService.SubmitJobApplication
            Return MyBase.Channel.SubmitJobApplication(request)
        End Function
        
        Public Function SubmitJobApplication(ByVal SubmitJobApplicationRequest As SubmitApp.SubmitJobApplicationRequest) As SubmitApp.SubmitJobApplicationResponse
            Dim inValue As SubmitApp.SubmitJobApplicationRequest1 = New SubmitApp.SubmitJobApplicationRequest1()
            inValue.SubmitJobApplicationRequest = SubmitJobApplicationRequest
            Dim retVal As SubmitApp.SubmitJobApplicationResponse1 = CType(Me,SubmitApp.IApplicationService).SubmitJobApplication(inValue)
            Return retVal.SubmitJobApplicationResponse
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SubmitApp_IApplicationService_BeginSubmitJobApplication(ByVal request As SubmitApp.SubmitJobApplicationRequest1, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements SubmitApp.IApplicationService.BeginSubmitJobApplication
            Return MyBase.Channel.BeginSubmitJobApplication(request, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BeginSubmitJobApplication(ByVal SubmitJobApplicationRequest As SubmitApp.SubmitJobApplicationRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim inValue As SubmitApp.SubmitJobApplicationRequest1 = New SubmitApp.SubmitJobApplicationRequest1()
            inValue.SubmitJobApplicationRequest = SubmitJobApplicationRequest
            Return CType(Me,SubmitApp.IApplicationService).BeginSubmitJobApplication(inValue, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SubmitApp_IApplicationService_EndSubmitJobApplication(ByVal result As System.IAsyncResult) As SubmitApp.SubmitJobApplicationResponse1 Implements SubmitApp.IApplicationService.EndSubmitJobApplication
            Return MyBase.Channel.EndSubmitJobApplication(result)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function EndSubmitJobApplication(ByVal result As System.IAsyncResult) As SubmitApp.SubmitJobApplicationResponse
            Dim retVal As SubmitApp.SubmitJobApplicationResponse1 = CType(Me,SubmitApp.IApplicationService).EndSubmitJobApplication(result)
            Return retVal.SubmitJobApplicationResponse
        End Function
        
        Private Function OnBeginSubmitJobApplication(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim SubmitJobApplicationRequest As SubmitApp.SubmitJobApplicationRequest = CType(inValues(0),SubmitApp.SubmitJobApplicationRequest)
            Return Me.BeginSubmitJobApplication(SubmitJobApplicationRequest, callback, asyncState)
        End Function
        
        Private Function OnEndSubmitJobApplication(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As SubmitApp.SubmitJobApplicationResponse = Me.EndSubmitJobApplication(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OnSubmitJobApplicationCompleted(ByVal state As Object)
            If (Not (Me.SubmitJobApplicationCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent SubmitJobApplicationCompleted(Me, New SubmitJobApplicationCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub SubmitJobApplicationAsync(ByVal SubmitJobApplicationRequest As SubmitApp.SubmitJobApplicationRequest)
            Me.SubmitJobApplicationAsync(SubmitJobApplicationRequest, Nothing)
        End Sub
        
        Public Overloads Sub SubmitJobApplicationAsync(ByVal SubmitJobApplicationRequest As SubmitApp.SubmitJobApplicationRequest, ByVal userState As Object)
            If (Me.onBeginSubmitJobApplicationDelegate Is Nothing) Then
                Me.onBeginSubmitJobApplicationDelegate = AddressOf Me.OnBeginSubmitJobApplication
            End If
            If (Me.onEndSubmitJobApplicationDelegate Is Nothing) Then
                Me.onEndSubmitJobApplicationDelegate = AddressOf Me.OnEndSubmitJobApplication
            End If
            If (Me.onSubmitJobApplicationCompletedDelegate Is Nothing) Then
                Me.onSubmitJobApplicationCompletedDelegate = AddressOf Me.OnSubmitJobApplicationCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginSubmitJobApplicationDelegate, New Object() {SubmitJobApplicationRequest}, Me.onEndSubmitJobApplicationDelegate, Me.onSubmitJobApplicationCompletedDelegate, userState)
        End Sub
    End Class
End Namespace
