// ----------------------------------------------------------------------------------
// Microsoft Developer & Platform Evangelism
// 
// Copyright (c) Microsoft Corporation. All rights reserved.
// 
// THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, 
// EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES 
// OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
// ----------------------------------------------------------------------------------
// The example companies, organizations, products, domain names,
// e-mail addresses, logos, people, places, and events depicted
// herein are fictitious.  No association with any real company,
// organization, product, domain name, email address, logo, person,
// places, or events is intended or should be inferred.
// ----------------------------------------------------------------------------------

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.208
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRApplicationServices.Application {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://contoso.com/hr/", ConfigurationName="Application.IApplicationService")]
    public interface IApplicationService {
        
        // CODEGEN: Generating message contract since the operation SubmitJobApplication is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://contoso.com/hr/IApplicationService/SubmitJobApplication", ReplyAction="http://contoso.com/hr/IApplicationService/SubmitJobApplicationResponse")]
        HRApplicationServices.Application.SubmitJobApplicationResponse SubmitJobApplication(HRApplicationServices.Application.SubmitJobApplicationRequest request);
        
        // CODEGEN: Generating message contract since the operation HumanScreeningCompleted is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://contoso.com/hr/IApplicationService/HumanScreeningCompleted", ReplyAction="http://contoso.com/hr/IApplicationService/HumanScreeningCompletedResponse")]
        HRApplicationServices.Application.HumanScreeningCompletedResponse HumanScreeningCompleted(HRApplicationServices.Application.HumanScreeningCompletedRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitJobApplicationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubmitJobApplicationRequest", Namespace="http://contoso.com/contracts/hr", Order=0)]
        public HRApplicationServices.Contracts.SubmitJobApplicationRequest SubmitJobApplicationRequest1;
        
        public SubmitJobApplicationRequest() {
        }
        
        public SubmitJobApplicationRequest(HRApplicationServices.Contracts.SubmitJobApplicationRequest SubmitJobApplicationRequest1) {
            this.SubmitJobApplicationRequest1 = SubmitJobApplicationRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitJobApplicationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubmitJobApplicationResponse", Namespace="http://contoso.com/contracts/hr", Order=0)]
        public HRApplicationServices.Contracts.SubmitJobApplicationResponse SubmitJobApplicationResponse1;
        
        public SubmitJobApplicationResponse() {
        }
        
        public SubmitJobApplicationResponse(HRApplicationServices.Contracts.SubmitJobApplicationResponse SubmitJobApplicationResponse1) {
            this.SubmitJobApplicationResponse1 = SubmitJobApplicationResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HumanScreeningCompletedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://contoso.com/contracts/hr", Order=0)]
        public HRApplicationServices.Contracts.HumanScreeningResult HumanScreeningResult;
        
        public HumanScreeningCompletedRequest() {
        }
        
        public HumanScreeningCompletedRequest(HRApplicationServices.Contracts.HumanScreeningResult HumanScreeningResult) {
            this.HumanScreeningResult = HumanScreeningResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HumanScreeningCompletedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/", Order=0)]
        public System.Nullable<bool> boolean;
        
        public HumanScreeningCompletedResponse() {
        }
        
        public HumanScreeningCompletedResponse(System.Nullable<bool> boolean) {
            this.boolean = boolean;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IApplicationServiceChannel : HRApplicationServices.Application.IApplicationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ApplicationServiceClient : System.ServiceModel.ClientBase<HRApplicationServices.Application.IApplicationService>, HRApplicationServices.Application.IApplicationService {
        
        public ApplicationServiceClient() {
        }
        
        public ApplicationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ApplicationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApplicationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApplicationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HRApplicationServices.Application.SubmitJobApplicationResponse HRApplicationServices.Application.IApplicationService.SubmitJobApplication(HRApplicationServices.Application.SubmitJobApplicationRequest request) {
            return base.Channel.SubmitJobApplication(request);
        }
        
        public HRApplicationServices.Contracts.SubmitJobApplicationResponse SubmitJobApplication(HRApplicationServices.Contracts.SubmitJobApplicationRequest SubmitJobApplicationRequest1) {
            HRApplicationServices.Application.SubmitJobApplicationRequest inValue = new HRApplicationServices.Application.SubmitJobApplicationRequest();
            inValue.SubmitJobApplicationRequest1 = SubmitJobApplicationRequest1;
            HRApplicationServices.Application.SubmitJobApplicationResponse retVal = ((HRApplicationServices.Application.IApplicationService)(this)).SubmitJobApplication(inValue);
            return retVal.SubmitJobApplicationResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HRApplicationServices.Application.HumanScreeningCompletedResponse HRApplicationServices.Application.IApplicationService.HumanScreeningCompleted(HRApplicationServices.Application.HumanScreeningCompletedRequest request) {
            return base.Channel.HumanScreeningCompleted(request);
        }
        
        public System.Nullable<bool> HumanScreeningCompleted(HRApplicationServices.Contracts.HumanScreeningResult HumanScreeningResult) {
            HRApplicationServices.Application.HumanScreeningCompletedRequest inValue = new HRApplicationServices.Application.HumanScreeningCompletedRequest();
            inValue.HumanScreeningResult = HumanScreeningResult;
            HRApplicationServices.Application.HumanScreeningCompletedResponse retVal = ((HRApplicationServices.Application.IApplicationService)(this)).HumanScreeningCompleted(inValue);
            return retVal.boolean;
        }
    }
}
