//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IMySingletonContract", SessionMode=System.ServiceModel.SessionMode.Required)]
public interface IMySingletonContract
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMySingletonContract/MyMethod", ReplyAction="http://tempuri.org/IMySingletonContract/MyMethodResponse")]
    void MyMethod();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IMySingletonContractChannel : IMySingletonContract, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class MySingletonContractClient : System.ServiceModel.ClientBase<IMySingletonContract>, IMySingletonContract
{
    
    public MySingletonContractClient()
    {
    }
    
    public MySingletonContractClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public MySingletonContractClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MySingletonContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MySingletonContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void MyMethod()
    {
        base.Channel.MyMethod();
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IMyOtherSingletonContract", SessionMode=System.ServiceModel.SessionMode.NotAllowed)]
public interface IMyOtherSingletonContract
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyOtherSingletonContract/MyOtherMethod", ReplyAction="http://tempuri.org/IMyOtherSingletonContract/MyOtherMethodResponse")]
    void MyOtherMethod();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IMyOtherSingletonContractChannel : IMyOtherSingletonContract, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class MyOtherSingletonContractClient : System.ServiceModel.ClientBase<IMyOtherSingletonContract>, IMyOtherSingletonContract
{
    
    public MyOtherSingletonContractClient()
    {
    }
    
    public MyOtherSingletonContractClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public MyOtherSingletonContractClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MyOtherSingletonContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MyOtherSingletonContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void MyOtherMethod()
    {
        base.Channel.MyOtherMethod();
    }
}
