' ----------------------------------------------------------------------------------
' Microsoft Developer & Platform Evangelism
' 
' Copyright (c) Microsoft Corporation. All rights reserved.
' 
' THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, 
' EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES 
' OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
' ----------------------------------------------------------------------------------
' The example companies, organizations, products, domain names,
' e-mail addresses, logos, people, places, and events depicted
' herein are fictitious.  No association with any real company,
' organization, product, domain name, email address, logo, person,
' places, or events is intended or should be inferred.
' ----------------------------------------------------------------------------------

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.21006.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class ServiceResources
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("HRApplicationServices.Activities.ServiceResources", GetType(ServiceResources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Your Application for Employment at Contoso.
        '''</summary>
        Public Shared ReadOnly Property ApplicationMailSubject() As String
            Get
                Return ResourceManager.GetString("ApplicationMailSubject", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid or empty education in resume.
        '''</summary>
        Public Shared ReadOnly Property ErrorEmptyEducation() As String
            Get
                Return ResourceManager.GetString("ErrorEmptyEducation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to We are unable to process your resume at this time - internal system error.
        '''</summary>
        Public Shared ReadOnly Property ExceptionMessage() As String
            Get
                Return ResourceManager.GetString("ExceptionMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        '''&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        '''&lt;head&gt;
        '''    &lt;title&gt;&lt;/title&gt;
        '''    &lt;style type=&quot;text/css&quot;&gt;
        '''        .style1
        '''        {{
        '''            width: 200px;
        '''            height: 68px;
        '''        }}
        '''        body
        '''        {{
        '''            font-family: Verdana;
        '''            font-size: large;
        '''        }}
        '''        &lt;/style&gt;
        '''&lt;/head&gt;
        '''&lt;body&gt;
        '''&lt;img src=&quot;{2}/Images/logo.png&quot; alt=&quot;Contoso Logo&quot; /&gt; [rest of string was truncated]&quot;;.
        '''</summary>
        Public Shared ReadOnly Property GenericMailTemplate() As String
            Get
                Return ResourceManager.GetString("GenericMailTemplate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Conguratulations.
        '''</summary>
        Public Shared ReadOnly Property HireHeading() As String
            Get
                Return ResourceManager.GetString("HireHeading", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Screening Request for Applicant {0}.
        '''</summary>
        Public Shared ReadOnly Property HumanScreenSubject() As String
            Get
                Return ResourceManager.GetString("HumanScreenSubject", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Thank you {0}, your applicant ID is {1}.  We are now processing resume and references.  You will receive an email with the results..
        '''</summary>
        Public Shared ReadOnly Property JobApplicationProcessing() As String
            Get
                Return ResourceManager.GetString("JobApplicationProcessing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Thank You.
        '''</summary>
        Public Shared ReadOnly Property NoHireHeading() As String
            Get
                Return ResourceManager.GetString("NoHireHeading", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dear {0}, after careful review, Contoso has decided that your qualifications did not match any current openings. Thank you for your interest..
        '''</summary>
        Public Shared ReadOnly Property NoHireText() As String
            Get
                Return ResourceManager.GetString("NoHireText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dear {0},  Contoso is pleased to extend you an offer. You should receive your $1,000,000 check for your signing bonus shortly..
        '''</summary>
        Public Shared ReadOnly Property OfferText() As String
            Get
                Return ResourceManager.GetString("OfferText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        '''&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        '''&lt;head&gt;
        '''    &lt;title&gt;&lt;/title&gt;
        '''    &lt;style type=&quot;text/css&quot;&gt;
        '''        .style1
        '''        {{
        '''            width: 200px;
        '''            height: 68px;
        '''        }}
        '''        body
        '''        {{
        '''            font-family: Verdana;
        '''            font-size: large;
        '''        }}
        '''        &lt;/style&gt;
        '''&lt;/head&gt;
        '''&lt;body&gt;
        '''&lt;img src=&quot;{2}/Images/logo.png&quot; alt=&quot;Contoso Logo&quot; /&gt; [rest of string was truncated]&quot;;.
        '''</summary>
        Public Shared ReadOnly Property ReviewMailTemplate() As String
            Get
                Return ResourceManager.GetString("ReviewMailTemplate", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
