//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Contact", Namespace="http://schemas.datacontract.org/2004/07/PersonService")]
    public partial class Contact : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MyClassOfint", Namespace="http://schemas.datacontract.org/2004/07/PersonService")]
    public partial class MyClassOfint : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int MyMemberField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MyMember
        {
            get
            {
                return this.MyMemberField;
            }
            set
            {
                this.MyMemberField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IContractManager")]
public interface IContractManager
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContractManager/AddContact", ReplyAction="http://tempuri.org/IContractManager/AddContactResponse")]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PersonService.Contact))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PersonService.MyClassOfint))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
    void AddContact(object contact);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContractManager/GetContacts", ReplyAction="http://tempuri.org/IContractManager/GetContactsResponse")]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PersonService.Contact))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PersonService.MyClassOfint))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
    object[] GetContacts();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContractManager/MyMethod", ReplyAction="http://tempuri.org/IContractManager/MyMethodResponse")]
    void MyMethod(PersonService.MyClassOfint obj);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IContractManagerChannel : IContractManager, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ContractManagerClient : System.ServiceModel.ClientBase<IContractManager>, IContractManager
{
    
    public ContractManagerClient()
    {
    }
    
    public ContractManagerClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ContractManagerClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ContractManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ContractManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void AddContact(object contact)
    {
        base.Channel.AddContact(contact);
    }
    
    public object[] GetContacts()
    {
        return base.Channel.GetContacts();
    }
    
    public void MyMethod(PersonService.MyClassOfint obj)
    {
        base.Channel.MyMethod(obj);
    }
}
