' ----------------------------------------------------------------------------------
' Microsoft Developer & Platform Evangelism
' 
' Copyright (c) Microsoft Corporation. All rights reserved.
' 
' THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, 
' EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES 
' OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
' ----------------------------------------------------------------------------------
' The example companies, organizations, products, domain names,
' e-mail addresses, logos, people, places, and events depicted
' herein are fictitious.  No association with any real company,
' organization, product, domain name, email address, logo, person,
' places, or events is intended or should be inferred.
' ----------------------------------------------------------------------------------

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30128.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Namespace Application
    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")> _
    Partial Public Class ApplicationServiceClient
        Inherits System.ServiceModel.ClientBase(Of Application.IApplicationService)
        Implements Application.IApplicationService

        Public Sub New()
            MyBase.New()
        End Sub

        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub

        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub

        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub

        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub

        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)> _
        Function Application_IApplicationService_SubmitJobApplication(ByVal request As Application.SubmitJobApplicationRequest) As Application.SubmitJobApplicationResponse Implements Application.IApplicationService.SubmitJobApplication
            Return MyBase.Channel.SubmitJobApplication(request)
        End Function

        Public Function SubmitJobApplication(ByVal SubmitJobApplicationRequest1 As HRApplicationServices.Contracts.SubmitJobApplicationRequest) As HRApplicationServices.Contracts.SubmitJobApplicationResponse
            Dim inValue As Application.SubmitJobApplicationRequest = New Application.SubmitJobApplicationRequest()
            inValue.SubmitJobApplicationRequest1 = SubmitJobApplicationRequest1
            Dim retVal As Application.SubmitJobApplicationResponse = CType(Me, Application.IApplicationService).SubmitJobApplication(inValue)
            Return retVal.SubmitJobApplicationResponse1
        End Function

        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)> _
        Function Application_IApplicationService_HumanScreeningCompleted(ByVal request As Application.HumanScreeningCompletedRequest) As Application.HumanScreeningCompletedResponse Implements Application.IApplicationService.HumanScreeningCompleted
            Return MyBase.Channel.HumanScreeningCompleted(request)
        End Function

        Public Function HumanScreeningCompleted(ByVal HumanScreeningResult As HRApplicationServices.Contracts.HumanScreeningResult) As System.Nullable(Of Boolean)
            Dim inValue As Application.HumanScreeningCompletedRequest = New Application.HumanScreeningCompletedRequest()
            inValue.HumanScreeningResult = HumanScreeningResult
            Dim retVal As Application.HumanScreeningCompletedResponse = CType(Me, Application.IApplicationService).HumanScreeningCompleted(inValue)
            Return retVal.[boolean]
        End Function
    End Class
End Namespace