' ----------------------------------------------------------------------------------
' Microsoft Developer & Platform Evangelism
' 
' Copyright (c) Microsoft Corporation. All rights reserved.
' 
' THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, 
' EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES 
' OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
' ----------------------------------------------------------------------------------
' The example companies, organizations, products, domain names,
' e-mail addresses, logos, people, places, and events depicted
' herein are fictitious.  No association with any real company,
' organization, product, domain name, email address, logo, person,
' places, or events is intended or should be inferred.
' ----------------------------------------------------------------------------------

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Collections.ObjectModel
Imports System.Collections.Specialized
Imports System.ComponentModel
Imports System.Globalization
Imports System.Runtime.Serialization
Imports System.Runtime.CompilerServices

<DataContract(IsReference:=True)>
<KnownType(GetType(ProductDescription))>
<KnownType(GetType(ProductModel))>
Partial Public Class ProductModelProductDescription
    Implements IObjectWithChangeTracker
    Implements INotifyPropertyChanged

#Region "Primitive Properties"

    <DataMember()>
    Public Property ProductModelID() As Integer
        Get
            Return _productModelID
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_productModelID, value) Then
                If ChangeTracker.ChangeTrackingEnabled AndAlso ChangeTracker.State <> ObjectState.Added Then
                    Throw New InvalidOperationException("The property 'ProductModelID' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.")
                End If
                If Not IsDeserializing Then
                    If ProductModel IsNot Nothing AndAlso Not Equals(ProductModel.ProductModelID, value) Then
                        ProductModel = Nothing
                    End If
                End If
                _productModelID = value
                OnPropertyChanged("ProductModelID")
            End If
        End Set
    End Property

    Private _productModelID As Integer

    <DataMember()>
    Public Property ProductDescriptionID() As Integer
        Get
            Return _productDescriptionID
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_productDescriptionID, value) Then
                If ChangeTracker.ChangeTrackingEnabled AndAlso ChangeTracker.State <> ObjectState.Added Then
                    Throw New InvalidOperationException("The property 'ProductDescriptionID' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.")
                End If
                If Not IsDeserializing Then
                    If ProductDescription IsNot Nothing AndAlso Not Equals(ProductDescription.ProductDescriptionID, value) Then
                        ProductDescription = Nothing
                    End If
                End If
                _productDescriptionID = value
                OnPropertyChanged("ProductDescriptionID")
            End If
        End Set
    End Property

    Private _productDescriptionID As Integer

    <DataMember()>
    Public Property Culture() As String
        Get
            Return _culture
        End Get
        Set(ByVal value As String)
            If Not Equals(_culture, value) Then
                If ChangeTracker.ChangeTrackingEnabled AndAlso ChangeTracker.State <> ObjectState.Added Then
                    Throw New InvalidOperationException("The property 'Culture' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.")
                End If
                _culture = value
                OnPropertyChanged("Culture")
            End If
        End Set
    End Property

    Private _culture As String

    <DataMember()>
    Public Property rowguid() As System.Guid
        Get
            Return _rowguid
        End Get
        Set(ByVal value As System.Guid)
            If Not Equals(_rowguid, value) Then
                _rowguid = value
                OnPropertyChanged("rowguid")
            End If
        End Set
    End Property

    Private _rowguid As System.Guid

    <DataMember()>
    Public Property ModifiedDate() As Date
        Get
            Return _modifiedDate
        End Get
        Set(ByVal value As Date)
            If Not Equals(_modifiedDate, value) Then
                _modifiedDate = value
                OnPropertyChanged("ModifiedDate")
            End If
        End Set
    End Property

    Private _modifiedDate As Date

#End Region
#Region "Navigation Properties"

    <DataMember()>
    Public Property ProductDescription() As ProductDescription
        Get
            Return _productDescription
        End Get
        Set(ByVal value As ProductDescription)
            If _productDescription IsNot value Then
                If ChangeTracker.ChangeTrackingEnabled AndAlso ChangeTracker.State <> ObjectState.Added AndAlso value IsNot Nothing Then
                    ' This the dependent end of an identifying relationship, so the principal end cannot be changed if it is already set,
                    ' otherwise it can only be set to an entity with a primary key that is the same value as the dependent's foreign key.
                    If Not Equals(ProductDescriptionID, value.ProductDescriptionID) Then
                        Throw New InvalidOperationException("The principal end of an identifying relationship can only be changed when the dependent end is in the Added state.")
                    End If
                End If
                Dim previousValue As ProductDescription = _productDescription
                _productDescription = value
                FixupProductDescription(previousValue)
                OnNavigationPropertyChanged("ProductDescription")
            End If
        End Set
    End Property

    Private _productDescription As ProductDescription


    <DataMember()>
    Public Property ProductModel() As ProductModel
        Get
            Return _productModel
        End Get
        Set(ByVal value As ProductModel)
            If _productModel IsNot value Then
                If ChangeTracker.ChangeTrackingEnabled AndAlso ChangeTracker.State <> ObjectState.Added AndAlso value IsNot Nothing Then
                    ' This the dependent end of an identifying relationship, so the principal end cannot be changed if it is already set,
                    ' otherwise it can only be set to an entity with a primary key that is the same value as the dependent's foreign key.
                    If Not Equals(ProductModelID, value.ProductModelID) Then
                        Throw New InvalidOperationException("The principal end of an identifying relationship can only be changed when the dependent end is in the Added state.")
                    End If
                End If
                Dim previousValue As ProductModel = _productModel
                _productModel = value
                FixupProductModel(previousValue)
                OnNavigationPropertyChanged("ProductModel")
            End If
        End Set
    End Property

    Private _productModel As ProductModel


#End Region
#Region "ChangeTracking"

    Protected Overridable Sub OnPropertyChanged(ByVal propertyName As String)
        If ChangeTracker.State <> ObjectState.Added AndAlso ChangeTracker.State <> ObjectState.Deleted Then
            ChangeTracker.State = ObjectState.Modified
        End If
        RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
    End Sub

    Protected Overridable Sub OnNavigationPropertyChanged(ByVal propertyName As String)
        RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
    End Sub

    Private Event PropertyChanged As PropertyChangedEventHandler Implements INotifyPropertyChanged.PropertyChanged
    Private _changeTracker As ObjectChangeTracker

    <DataMember()>
    Public Property ChangeTracker() As ObjectChangeTracker Implements IObjectWithChangeTracker.ChangeTracker
        Get
            If _changeTracker Is Nothing Then
                _changeTracker = New ObjectChangeTracker()
                AddHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
            Return _changeTracker
        End Get
        Set(ByVal value As ObjectChangeTracker)
            If _changeTracker IsNot Nothing Then
                RemoveHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
            _changeTracker = value
            If _changeTracker IsNot Nothing Then
                AddHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
        End Set
    End Property

    Private Sub HandleObjectStateChanging(ByVal sender As Object, ByVal e As ObjectStateChangingEventArgs)
        If e.NewState = ObjectState.Deleted Then
            Me.ClearNavigationProperties()
        End If
    End Sub

    ' This entity type is the dependent end in at least one association that performs cascade deletes.
    ' This event handler will process notifications that occur when the principal end is deleted.
    Friend Sub HandleCascadeDelete(ByVal sender As Object, ByVal e As ObjectStateChangingEventArgs)
        If e.NewState = ObjectState.Deleted Then
            Me.MarkAsDeleted()
        End If
    End Sub

    Private _isDeserializing As Boolean
    Protected Property IsDeserializing() As Boolean
        Get
            Return _isDeserializing
        End Get
        Private Set(ByVal value As Boolean)
            _isDeserializing = value
        End Set
    End Property

    <OnDeserializing()>
    Public Sub OnDeserializingMethod(ByVal context As StreamingContext)
        IsDeserializing = True
    End Sub

    <OnDeserialized()>
    Public Sub OnDeserializedMethod(ByVal context As StreamingContext)
        IsDeserializing = False
        ChangeTracker.ChangeTrackingEnabled = True
    End Sub

    Protected Overridable Sub ClearNavigationProperties()
        ProductDescription = Nothing
        ProductModel = Nothing
    End Sub

#End Region
#Region "Association Fixup"

    Private Sub FixupProductDescription(ByVal previousValue As ProductDescription)
        If IsDeserializing Then
            Return
        End If

        If previousValue IsNot Nothing AndAlso previousValue.ProductModelProductDescriptions.Contains(Me) Then
            previousValue.ProductModelProductDescriptions.Remove(Me)
        End If

        If ProductDescription IsNot Nothing Then
            If Not ProductDescription.ProductModelProductDescriptions.Contains(Me) Then
                ProductDescription.ProductModelProductDescriptions.Add(Me)
            End If

            ProductDescriptionID = ProductDescription.ProductDescriptionID
        End If
        If ChangeTracker.ChangeTrackingEnabled Then
            If ChangeTracker.OriginalValues.ContainsKey("ProductDescription") AndAlso
                ChangeTracker.OriginalValues("ProductDescription") Is ProductDescription Then
                ChangeTracker.OriginalValues.Remove("ProductDescription")
            Else
                ChangeTracker.RecordOriginalValue("ProductDescription", previousValue)
            End If
            If ProductDescription IsNot Nothing AndAlso Not ProductDescription.ChangeTracker.ChangeTrackingEnabled Then
                ProductDescription.StartTracking()
            End If
        End If
    End Sub

    Private Sub FixupProductModel(ByVal previousValue As ProductModel)
        If IsDeserializing Then
            Return
        End If

        If previousValue IsNot Nothing AndAlso previousValue.ProductModelProductDescriptions.Contains(Me) Then
            previousValue.ProductModelProductDescriptions.Remove(Me)
        End If

        If ProductModel IsNot Nothing Then
            If Not ProductModel.ProductModelProductDescriptions.Contains(Me) Then
                ProductModel.ProductModelProductDescriptions.Add(Me)
            End If

            ProductModelID = ProductModel.ProductModelID
        End If
        If ChangeTracker.ChangeTrackingEnabled Then
            If ChangeTracker.OriginalValues.ContainsKey("ProductModel") AndAlso
                ChangeTracker.OriginalValues("ProductModel") Is ProductModel Then
                ChangeTracker.OriginalValues.Remove("ProductModel")
            Else
                ChangeTracker.RecordOriginalValue("ProductModel", previousValue)
            End If
            If ProductModel IsNot Nothing AndAlso Not ProductModel.ChangeTracker.ChangeTrackingEnabled Then
                ProductModel.StartTracking()
            End If
        End If
    End Sub

#End Region
End Class
