' ----------------------------------------------------------------------------------
' Microsoft Developer & Platform Evangelism
' 
' Copyright (c) Microsoft Corporation. All rights reserved.
' 
' THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, 
' EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES 
' OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
' ----------------------------------------------------------------------------------
' The example companies, organizations, products, domain names,
' e-mail addresses, logos, people, places, and events depicted
' herein are fictitious.  No association with any real company,
' organization, product, domain name, email address, logo, person,
' places, or events is intended or should be inferred.
' ----------------------------------------------------------------------------------

'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Data.EntityClient
Imports System.ComponentModel
Imports System.Xml.Serialization
Imports System.Runtime.Serialization

<Assembly: EdmSchemaAttribute()>
#Region "EDM Relationship Metadata"

<Assembly: EdmRelationshipAttribute("AdventureWorksLT_DataModel", "FK_SalesOrderHeader_Customer_CustomerID", "Customer", Metadata.Edm.RelationshipMultiplicity.One, GetType(UsingWCFServices.Web.Models.Customer), "SalesOrderHeader", Metadata.Edm.RelationshipMultiplicity.Many, GetType(UsingWCFServices.Web.Models.SalesOrderHeader), True)>

#End Region

Namespace UsingWCFServices.Web.Models
	#Region "Contexts"

	''' <summary>
	''' No Metadata Documentation available.
	''' </summary>
	Partial Public Class AdventureWorksLT_DataEntities
		Inherits ObjectContext
		#Region "Constructors"

		''' <summary>
		''' Initializes a new AdventureWorksLT_DataEntities object using the connection string found in the 'AdventureWorksLT_DataEntities' section of the application configuration file.
		''' </summary>
		Public Sub New()
			MyBase.New("name=AdventureWorksLT_DataEntities", "AdventureWorksLT_DataEntities")
			Me.ContextOptions.LazyLoadingEnabled = True
			OnContextCreated()
		End Sub

		''' <summary>
		''' Initialize a new AdventureWorksLT_DataEntities object.
		''' </summary>
		Public Sub New(ByVal connectionString As String)
			MyBase.New(connectionString, "AdventureWorksLT_DataEntities")
			Me.ContextOptions.LazyLoadingEnabled = True
			OnContextCreated()
		End Sub

		''' <summary>
		''' Initialize a new AdventureWorksLT_DataEntities object.
		''' </summary>
		Public Sub New(ByVal connection As EntityConnection)
			MyBase.New(connection, "AdventureWorksLT_DataEntities")
			Me.ContextOptions.LazyLoadingEnabled = True
			OnContextCreated()
		End Sub

		#End Region

		#Region "Partial Methods"

		Partial Private Sub OnContextCreated()
		End Sub

		#End Region

		#Region "ObjectSet Properties"

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		Public ReadOnly Property Customers() As ObjectSet(Of Customer)
			Get
				If (_Customers Is Nothing) Then
					_Customers = MyBase.CreateObjectSet(Of Customer)("Customers")
				End If
				Return _Customers
			End Get
		End Property
		Private _Customers As ObjectSet(Of Customer)

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		Public ReadOnly Property SalesOrderHeaders() As ObjectSet(Of SalesOrderHeader)
			Get
				If (_SalesOrderHeaders Is Nothing) Then
					_SalesOrderHeaders = MyBase.CreateObjectSet(Of SalesOrderHeader)("SalesOrderHeaders")
				End If
				Return _SalesOrderHeaders
			End Get
		End Property
		Private _SalesOrderHeaders As ObjectSet(Of SalesOrderHeader)

		#End Region
		#Region "AddTo Methods"

		''' <summary>
		''' Deprecated Method for adding a new object to the Customers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
		''' </summary>
		Public Sub AddToCustomers(ByVal customer_Renamed As Customer)
			MyBase.AddObject("Customers", customer_Renamed)
		End Sub

		''' <summary>
		''' Deprecated Method for adding a new object to the SalesOrderHeaders EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
		''' </summary>
		Public Sub AddToSalesOrderHeaders(ByVal salesOrderHeader_Renamed As SalesOrderHeader)
			MyBase.AddObject("SalesOrderHeaders", salesOrderHeader_Renamed)
		End Sub

		#End Region
	End Class


	#End Region

	#Region "Entities"

	''' <summary>
	''' No Metadata Documentation available.
	''' </summary>
	<EdmEntityTypeAttribute(NamespaceName:="AdventureWorksLT_DataModel", Name:="Customer"), Serializable(), DataContractAttribute(IsReference:=True)>
	Partial Public Class Customer
		Inherits EntityObject
		#Region "Factory Method"

		''' <summary>
		''' Create a new Customer object.
		''' </summary>
		''' <param name="customerID">Initial value of the CustomerID property.</param>
		''' <param name="nameStyle">Initial value of the NameStyle property.</param>
		''' <param name="firstName">Initial value of the FirstName property.</param>
		''' <param name="lastName">Initial value of the LastName property.</param>
		''' <param name="passwordHash">Initial value of the PasswordHash property.</param>
		''' <param name="passwordSalt">Initial value of the PasswordSalt property.</param>
		''' <param name="rowguid">Initial value of the rowguid property.</param>
		''' <param name="modifiedDate">Initial value of the ModifiedDate property.</param>
		Public Shared Function CreateCustomer(ByVal customerID As Global.System.Int32, ByVal nameStyle As Global.System.Boolean, ByVal firstName As Global.System.String, ByVal lastName As Global.System.String, ByVal passwordHash As Global.System.String, ByVal passwordSalt As Global.System.String, ByVal rowguid As Global.System.Guid, ByVal modifiedDate As Date) As Customer
			Dim customer_Renamed As New Customer()
			customer_Renamed.CustomerID = customerID
			customer_Renamed.NameStyle = nameStyle
			customer_Renamed.FirstName = firstName
			customer_Renamed.LastName = lastName
			customer_Renamed.PasswordHash = passwordHash
			customer_Renamed.PasswordSalt = passwordSalt
			customer_Renamed.rowguid = rowguid
			customer_Renamed.ModifiedDate = modifiedDate
			Return customer_Renamed
		End Function

		#End Region
		#Region "Primitive Properties"

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=True, IsNullable:=False), DataMemberAttribute()>
		Public Property CustomerID() As Global.System.Int32
			Get
				Return _CustomerID
			End Get
			Set(ByVal value As Int32)
				If _CustomerID <> value Then
					OnCustomerIDChanging(value)
					ReportPropertyChanging("CustomerID")
					_CustomerID = StructuralObject.SetValidValue(value)
					ReportPropertyChanged("CustomerID")
					OnCustomerIDChanged()
				End If
			End Set
		End Property
		Private _CustomerID As Global.System.Int32
		Partial Private Sub OnCustomerIDChanging(ByVal value As Global.System.Int32)
		End Sub
		Partial Private Sub OnCustomerIDChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=False), DataMemberAttribute()>
		Public Property NameStyle() As Global.System.Boolean
			Get
				Return _NameStyle
			End Get
			Set(ByVal value As Boolean)
				OnNameStyleChanging(value)
				ReportPropertyChanging("NameStyle")
				_NameStyle = StructuralObject.SetValidValue(value)
				ReportPropertyChanged("NameStyle")
				OnNameStyleChanged()
			End Set
		End Property
		Private _NameStyle As Global.System.Boolean
		Partial Private Sub OnNameStyleChanging(ByVal value As Global.System.Boolean)
		End Sub
		Partial Private Sub OnNameStyleChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True), DataMemberAttribute()>
		Public Property Title() As Global.System.String
			Get
				Return _Title
			End Get
			Set(ByVal value As String)
				OnTitleChanging(value)
				ReportPropertyChanging("Title")
				_Title = StructuralObject.SetValidValue(value, True)
				ReportPropertyChanged("Title")
				OnTitleChanged()
			End Set
		End Property
		Private _Title As Global.System.String
		Partial Private Sub OnTitleChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnTitleChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=False), DataMemberAttribute()>
		Public Property FirstName() As Global.System.String
			Get
				Return _FirstName
			End Get
			Set(ByVal value As String)
				OnFirstNameChanging(value)
				ReportPropertyChanging("FirstName")
				_FirstName = StructuralObject.SetValidValue(value, False)
				ReportPropertyChanged("FirstName")
				OnFirstNameChanged()
			End Set
		End Property
		Private _FirstName As Global.System.String
		Partial Private Sub OnFirstNameChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnFirstNameChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True), DataMemberAttribute()>
		Public Property MiddleName() As Global.System.String
			Get
				Return _MiddleName
			End Get
			Set(ByVal value As String)
				OnMiddleNameChanging(value)
				ReportPropertyChanging("MiddleName")
				_MiddleName = StructuralObject.SetValidValue(value, True)
				ReportPropertyChanged("MiddleName")
				OnMiddleNameChanged()
			End Set
		End Property
		Private _MiddleName As Global.System.String
		Partial Private Sub OnMiddleNameChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnMiddleNameChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=False), DataMemberAttribute()>
		Public Property LastName() As Global.System.String
			Get
				Return _LastName
			End Get
			Set(ByVal value As String)
				OnLastNameChanging(value)
				ReportPropertyChanging("LastName")
				_LastName = StructuralObject.SetValidValue(value, False)
				ReportPropertyChanged("LastName")
				OnLastNameChanged()
			End Set
		End Property
		Private _LastName As Global.System.String
		Partial Private Sub OnLastNameChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnLastNameChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True), DataMemberAttribute()>
		Public Property Suffix() As Global.System.String
			Get
				Return _Suffix
			End Get
			Set(ByVal value As String)
				OnSuffixChanging(value)
				ReportPropertyChanging("Suffix")
				_Suffix = StructuralObject.SetValidValue(value, True)
				ReportPropertyChanged("Suffix")
				OnSuffixChanged()
			End Set
		End Property
		Private _Suffix As Global.System.String
		Partial Private Sub OnSuffixChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnSuffixChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True), DataMemberAttribute()>
		Public Property CompanyName() As Global.System.String
			Get
				Return _CompanyName
			End Get
			Set(ByVal value As String)
				OnCompanyNameChanging(value)
				ReportPropertyChanging("CompanyName")
				_CompanyName = StructuralObject.SetValidValue(value, True)
				ReportPropertyChanged("CompanyName")
				OnCompanyNameChanged()
			End Set
		End Property
		Private _CompanyName As Global.System.String
		Partial Private Sub OnCompanyNameChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnCompanyNameChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True), DataMemberAttribute()>
		Public Property SalesPerson() As Global.System.String
			Get
				Return _SalesPerson
			End Get
			Set(ByVal value As String)
				OnSalesPersonChanging(value)
				ReportPropertyChanging("SalesPerson")
				_SalesPerson = StructuralObject.SetValidValue(value, True)
				ReportPropertyChanged("SalesPerson")
				OnSalesPersonChanged()
			End Set
		End Property
		Private _SalesPerson As Global.System.String
		Partial Private Sub OnSalesPersonChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnSalesPersonChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True), DataMemberAttribute()>
		Public Property EmailAddress() As Global.System.String
			Get
				Return _EmailAddress
			End Get
			Set(ByVal value As String)
				OnEmailAddressChanging(value)
				ReportPropertyChanging("EmailAddress")
				_EmailAddress = StructuralObject.SetValidValue(value, True)
				ReportPropertyChanged("EmailAddress")
				OnEmailAddressChanged()
			End Set
		End Property
		Private _EmailAddress As Global.System.String
		Partial Private Sub OnEmailAddressChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnEmailAddressChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True), DataMemberAttribute()>
		Public Property Phone() As Global.System.String
			Get
				Return _Phone
			End Get
			Set(ByVal value As String)
				OnPhoneChanging(value)
				ReportPropertyChanging("Phone")
				_Phone = StructuralObject.SetValidValue(value, True)
				ReportPropertyChanged("Phone")
				OnPhoneChanged()
			End Set
		End Property
		Private _Phone As Global.System.String
		Partial Private Sub OnPhoneChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnPhoneChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=False), DataMemberAttribute()>
		Public Property PasswordHash() As Global.System.String
			Get
				Return _PasswordHash
			End Get
			Set(ByVal value As String)
				OnPasswordHashChanging(value)
				ReportPropertyChanging("PasswordHash")
				_PasswordHash = StructuralObject.SetValidValue(value, False)
				ReportPropertyChanged("PasswordHash")
				OnPasswordHashChanged()
			End Set
		End Property
		Private _PasswordHash As Global.System.String
		Partial Private Sub OnPasswordHashChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnPasswordHashChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=False), DataMemberAttribute()>
		Public Property PasswordSalt() As Global.System.String
			Get
				Return _PasswordSalt
			End Get
			Set(ByVal value As String)
				OnPasswordSaltChanging(value)
				ReportPropertyChanging("PasswordSalt")
				_PasswordSalt = StructuralObject.SetValidValue(value, False)
				ReportPropertyChanged("PasswordSalt")
				OnPasswordSaltChanged()
			End Set
		End Property
		Private _PasswordSalt As Global.System.String
		Partial Private Sub OnPasswordSaltChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnPasswordSaltChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=False), DataMemberAttribute()>
		Public Property rowguid() As Global.System.Guid
			Get
				Return _rowguid
			End Get
			Set(ByVal value As Guid)
				OnrowguidChanging(value)
				ReportPropertyChanging("rowguid")
				_rowguid = StructuralObject.SetValidValue(value)
				ReportPropertyChanged("rowguid")
				OnrowguidChanged()
			End Set
		End Property
		Private _rowguid As Global.System.Guid
		Partial Private Sub OnrowguidChanging(ByVal value As Global.System.Guid)
		End Sub
		Partial Private Sub OnrowguidChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=False), DataMemberAttribute()>
		Public Property ModifiedDate() As Date
			Get
				Return _ModifiedDate
			End Get
			Set(ByVal value As Date)
				OnModifiedDateChanging(value)
				ReportPropertyChanging("ModifiedDate")
				_ModifiedDate = StructuralObject.SetValidValue(value)
				ReportPropertyChanged("ModifiedDate")
				OnModifiedDateChanged()
			End Set
		End Property
		Private _ModifiedDate As Date
		Partial Private Sub OnModifiedDateChanging(ByVal value As Date)
		End Sub
		Partial Private Sub OnModifiedDateChanged()
		End Sub

		#End Region

		#Region "Navigation Properties"

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<XmlIgnoreAttribute(), SoapIgnoreAttribute(), DataMemberAttribute(), EdmRelationshipNavigationPropertyAttribute("AdventureWorksLT_DataModel", "FK_SalesOrderHeader_Customer_CustomerID", "SalesOrderHeader")>
		Public Property SalesOrderHeaders() As EntityCollection(Of SalesOrderHeader)
			Get
				Return (CType(Me, IEntityWithRelationships)).RelationshipManager.GetRelatedCollection(Of SalesOrderHeader)("AdventureWorksLT_DataModel.FK_SalesOrderHeader_Customer_CustomerID", "SalesOrderHeader")
			End Get
			Set(ByVal value As EntityCollection(Of SalesOrderHeader))
				If (value IsNot Nothing) Then
					CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of SalesOrderHeader)("AdventureWorksLT_DataModel.FK_SalesOrderHeader_Customer_CustomerID", "SalesOrderHeader", value)
				End If
			End Set
		End Property

		#End Region
	End Class

	''' <summary>
	''' No Metadata Documentation available.
	''' </summary>
	<EdmEntityTypeAttribute(NamespaceName:="AdventureWorksLT_DataModel", Name:="SalesOrderHeader"), Serializable(), DataContractAttribute(IsReference:=True)>
	Partial Public Class SalesOrderHeader
		Inherits EntityObject
		#Region "Factory Method"

		''' <summary>
		''' Create a new SalesOrderHeader object.
		''' </summary>
		''' <param name="salesOrderID">Initial value of the SalesOrderID property.</param>
		''' <param name="revisionNumber">Initial value of the RevisionNumber property.</param>
		''' <param name="orderDate">Initial value of the OrderDate property.</param>
		''' <param name="dueDate">Initial value of the DueDate property.</param>
		''' <param name="status">Initial value of the Status property.</param>
		''' <param name="onlineOrderFlag">Initial value of the OnlineOrderFlag property.</param>
		''' <param name="salesOrderNumber">Initial value of the SalesOrderNumber property.</param>
		''' <param name="customerID">Initial value of the CustomerID property.</param>
		''' <param name="shipMethod">Initial value of the ShipMethod property.</param>
		''' <param name="subTotal">Initial value of the SubTotal property.</param>
		''' <param name="taxAmt">Initial value of the TaxAmt property.</param>
		''' <param name="freight">Initial value of the Freight property.</param>
		''' <param name="totalDue">Initial value of the TotalDue property.</param>
		''' <param name="rowguid">Initial value of the rowguid property.</param>
		''' <param name="modifiedDate">Initial value of the ModifiedDate property.</param>
		Public Shared Function CreateSalesOrderHeader(ByVal salesOrderID As Global.System.Int32, ByVal revisionNumber As Global.System.Byte, ByVal orderDate As Date, ByVal dueDate As Date, ByVal status As Global.System.Byte, ByVal onlineOrderFlag As Global.System.Boolean, ByVal salesOrderNumber As Global.System.String, ByVal customerID As Global.System.Int32, ByVal shipMethod As Global.System.String, ByVal subTotal As Global.System.Decimal, ByVal taxAmt As Global.System.Decimal, ByVal freight As Global.System.Decimal, ByVal totalDue As Global.System.Decimal, ByVal rowguid As Global.System.Guid, ByVal modifiedDate As Date) As SalesOrderHeader
			Dim salesOrderHeader_Renamed As New SalesOrderHeader()
			salesOrderHeader_Renamed.SalesOrderID = salesOrderID
			salesOrderHeader_Renamed.RevisionNumber = revisionNumber
			salesOrderHeader_Renamed.OrderDate = orderDate
			salesOrderHeader_Renamed.DueDate = dueDate
			salesOrderHeader_Renamed.Status = status
			salesOrderHeader_Renamed.OnlineOrderFlag = onlineOrderFlag
			salesOrderHeader_Renamed.SalesOrderNumber = salesOrderNumber
			salesOrderHeader_Renamed.CustomerID = customerID
			salesOrderHeader_Renamed.ShipMethod = shipMethod
			salesOrderHeader_Renamed.SubTotal = subTotal
			salesOrderHeader_Renamed.TaxAmt = taxAmt
			salesOrderHeader_Renamed.Freight = freight
			salesOrderHeader_Renamed.TotalDue = totalDue
			salesOrderHeader_Renamed.rowguid = rowguid
			salesOrderHeader_Renamed.ModifiedDate = modifiedDate
			Return salesOrderHeader_Renamed
		End Function

		#End Region
		#Region "Primitive Properties"

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=True, IsNullable:=False), DataMemberAttribute()>
		Public Property SalesOrderID() As Global.System.Int32
			Get
				Return _SalesOrderID
			End Get
			Set(ByVal value As Int32)
				If _SalesOrderID <> value Then
					OnSalesOrderIDChanging(value)
					ReportPropertyChanging("SalesOrderID")
					_SalesOrderID = StructuralObject.SetValidValue(value)
					ReportPropertyChanged("SalesOrderID")
					OnSalesOrderIDChanged()
				End If
			End Set
		End Property
		Private _SalesOrderID As Global.System.Int32
		Partial Private Sub OnSalesOrderIDChanging(ByVal value As Global.System.Int32)
		End Sub
		Partial Private Sub OnSalesOrderIDChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=False), DataMemberAttribute()>
		Public Property RevisionNumber() As Global.System.Byte
			Get
				Return _RevisionNumber
			End Get
			Set(ByVal value As Byte)
				OnRevisionNumberChanging(value)
				ReportPropertyChanging("RevisionNumber")
				_RevisionNumber = StructuralObject.SetValidValue(value)
				ReportPropertyChanged("RevisionNumber")
				OnRevisionNumberChanged()
			End Set
		End Property
		Private _RevisionNumber As Global.System.Byte
		Partial Private Sub OnRevisionNumberChanging(ByVal value As Global.System.Byte)
		End Sub
		Partial Private Sub OnRevisionNumberChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=False), DataMemberAttribute()>
		Public Property OrderDate() As Date
			Get
				Return _OrderDate
			End Get
			Set(ByVal value As Date)
				OnOrderDateChanging(value)
				ReportPropertyChanging("OrderDate")
				_OrderDate = StructuralObject.SetValidValue(value)
				ReportPropertyChanged("OrderDate")
				OnOrderDateChanged()
			End Set
		End Property
		Private _OrderDate As Date
		Partial Private Sub OnOrderDateChanging(ByVal value As Date)
		End Sub
		Partial Private Sub OnOrderDateChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=False), DataMemberAttribute()>
		Public Property DueDate() As Date
			Get
				Return _DueDate
			End Get
			Set(ByVal value As Date)
				OnDueDateChanging(value)
				ReportPropertyChanging("DueDate")
				_DueDate = StructuralObject.SetValidValue(value)
				ReportPropertyChanged("DueDate")
				OnDueDateChanged()
			End Set
		End Property
		Private _DueDate As Date
		Partial Private Sub OnDueDateChanging(ByVal value As Date)
		End Sub
		Partial Private Sub OnDueDateChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True), DataMemberAttribute()>
		Public Property ShipDate() As Global.System.DateTime?
			Get
				Return _ShipDate
			End Get
			Set(ByVal value? As Date)
				OnShipDateChanging(value)
				ReportPropertyChanging("ShipDate")
				_ShipDate = StructuralObject.SetValidValue(value)
				ReportPropertyChanged("ShipDate")
				OnShipDateChanged()
			End Set
		End Property
		Private _ShipDate? As Global.System.DateTime
		Partial Private Sub OnShipDateChanging(ByVal value? As Global.System.DateTime)
		End Sub
		Partial Private Sub OnShipDateChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=False), DataMemberAttribute()>
		Public Property Status() As Global.System.Byte
			Get
				Return _Status
			End Get
			Set(ByVal value As Byte)
				OnStatusChanging(value)
				ReportPropertyChanging("Status")
				_Status = StructuralObject.SetValidValue(value)
				ReportPropertyChanged("Status")
				OnStatusChanged()
			End Set
		End Property
		Private _Status As Global.System.Byte
		Partial Private Sub OnStatusChanging(ByVal value As Global.System.Byte)
		End Sub
		Partial Private Sub OnStatusChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=False), DataMemberAttribute()>
		Public Property OnlineOrderFlag() As Global.System.Boolean
			Get
				Return _OnlineOrderFlag
			End Get
			Set(ByVal value As Boolean)
				OnOnlineOrderFlagChanging(value)
				ReportPropertyChanging("OnlineOrderFlag")
				_OnlineOrderFlag = StructuralObject.SetValidValue(value)
				ReportPropertyChanged("OnlineOrderFlag")
				OnOnlineOrderFlagChanged()
			End Set
		End Property
		Private _OnlineOrderFlag As Global.System.Boolean
		Partial Private Sub OnOnlineOrderFlagChanging(ByVal value As Global.System.Boolean)
		End Sub
		Partial Private Sub OnOnlineOrderFlagChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=False), DataMemberAttribute()>
		Public Property SalesOrderNumber() As Global.System.String
			Get
				Return _SalesOrderNumber
			End Get
			Set(ByVal value As String)
				OnSalesOrderNumberChanging(value)
				ReportPropertyChanging("SalesOrderNumber")
				_SalesOrderNumber = StructuralObject.SetValidValue(value, True)
				ReportPropertyChanged("SalesOrderNumber")
				OnSalesOrderNumberChanged()
			End Set
		End Property
		Private _SalesOrderNumber As Global.System.String
		Partial Private Sub OnSalesOrderNumberChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnSalesOrderNumberChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True), DataMemberAttribute()>
		Public Property PurchaseOrderNumber() As Global.System.String
			Get
				Return _PurchaseOrderNumber
			End Get
			Set(ByVal value As String)
				OnPurchaseOrderNumberChanging(value)
				ReportPropertyChanging("PurchaseOrderNumber")
				_PurchaseOrderNumber = StructuralObject.SetValidValue(value, True)
				ReportPropertyChanged("PurchaseOrderNumber")
				OnPurchaseOrderNumberChanged()
			End Set
		End Property
		Private _PurchaseOrderNumber As Global.System.String
		Partial Private Sub OnPurchaseOrderNumberChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnPurchaseOrderNumberChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True), DataMemberAttribute()>
		Public Property AccountNumber() As Global.System.String
			Get
				Return _AccountNumber
			End Get
			Set(ByVal value As String)
				OnAccountNumberChanging(value)
				ReportPropertyChanging("AccountNumber")
				_AccountNumber = StructuralObject.SetValidValue(value, True)
				ReportPropertyChanged("AccountNumber")
				OnAccountNumberChanged()
			End Set
		End Property
		Private _AccountNumber As Global.System.String
		Partial Private Sub OnAccountNumberChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnAccountNumberChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=False), DataMemberAttribute()>
		Public Property CustomerID() As Global.System.Int32
			Get
				Return _CustomerID
			End Get
			Set(ByVal value As Int32)
				OnCustomerIDChanging(value)
				ReportPropertyChanging("CustomerID")
				_CustomerID = StructuralObject.SetValidValue(value)
				ReportPropertyChanged("CustomerID")
				OnCustomerIDChanged()
			End Set
		End Property
		Private _CustomerID As Global.System.Int32
		Partial Private Sub OnCustomerIDChanging(ByVal value As Global.System.Int32)
		End Sub
		Partial Private Sub OnCustomerIDChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True), DataMemberAttribute()>
		Public Property ShipToAddressID() As Global.System.Int32?
			Get
				Return _ShipToAddressID
			End Get
			Set(ByVal value? As Int32)
				OnShipToAddressIDChanging(value)
				ReportPropertyChanging("ShipToAddressID")
				_ShipToAddressID = StructuralObject.SetValidValue(value)
				ReportPropertyChanged("ShipToAddressID")
				OnShipToAddressIDChanged()
			End Set
		End Property
		Private _ShipToAddressID? As Global.System.Int32
		Partial Private Sub OnShipToAddressIDChanging(ByVal value? As Global.System.Int32)
		End Sub
		Partial Private Sub OnShipToAddressIDChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True), DataMemberAttribute()>
		Public Property BillToAddressID() As Global.System.Int32?
			Get
				Return _BillToAddressID
			End Get
			Set(ByVal value? As Int32)
				OnBillToAddressIDChanging(value)
				ReportPropertyChanging("BillToAddressID")
				_BillToAddressID = StructuralObject.SetValidValue(value)
				ReportPropertyChanged("BillToAddressID")
				OnBillToAddressIDChanged()
			End Set
		End Property
		Private _BillToAddressID? As Global.System.Int32
		Partial Private Sub OnBillToAddressIDChanging(ByVal value? As Global.System.Int32)
		End Sub
		Partial Private Sub OnBillToAddressIDChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=False), DataMemberAttribute()>
		Public Property ShipMethod() As Global.System.String
			Get
				Return _ShipMethod
			End Get
			Set(ByVal value As String)
				OnShipMethodChanging(value)
				ReportPropertyChanging("ShipMethod")
				_ShipMethod = StructuralObject.SetValidValue(value, False)
				ReportPropertyChanged("ShipMethod")
				OnShipMethodChanged()
			End Set
		End Property
		Private _ShipMethod As Global.System.String
		Partial Private Sub OnShipMethodChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnShipMethodChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True), DataMemberAttribute()>
		Public Property CreditCardApprovalCode() As Global.System.String
			Get
				Return _CreditCardApprovalCode
			End Get
			Set(ByVal value As String)
				OnCreditCardApprovalCodeChanging(value)
				ReportPropertyChanging("CreditCardApprovalCode")
				_CreditCardApprovalCode = StructuralObject.SetValidValue(value, True)
				ReportPropertyChanged("CreditCardApprovalCode")
				OnCreditCardApprovalCodeChanged()
			End Set
		End Property
		Private _CreditCardApprovalCode As Global.System.String
		Partial Private Sub OnCreditCardApprovalCodeChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnCreditCardApprovalCodeChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=False), DataMemberAttribute()>
		Public Property SubTotal() As Global.System.Decimal
			Get
				Return _SubTotal
			End Get
			Set(ByVal value As Decimal)
				OnSubTotalChanging(value)
				ReportPropertyChanging("SubTotal")
				_SubTotal = StructuralObject.SetValidValue(value)
				ReportPropertyChanged("SubTotal")
				OnSubTotalChanged()
			End Set
		End Property
		Private _SubTotal As Global.System.Decimal
		Partial Private Sub OnSubTotalChanging(ByVal value As Global.System.Decimal)
		End Sub
		Partial Private Sub OnSubTotalChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=False), DataMemberAttribute()>
		Public Property TaxAmt() As Global.System.Decimal
			Get
				Return _TaxAmt
			End Get
			Set(ByVal value As Decimal)
				OnTaxAmtChanging(value)
				ReportPropertyChanging("TaxAmt")
				_TaxAmt = StructuralObject.SetValidValue(value)
				ReportPropertyChanged("TaxAmt")
				OnTaxAmtChanged()
			End Set
		End Property
		Private _TaxAmt As Global.System.Decimal
		Partial Private Sub OnTaxAmtChanging(ByVal value As Global.System.Decimal)
		End Sub
		Partial Private Sub OnTaxAmtChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=False), DataMemberAttribute()>
		Public Property Freight() As Global.System.Decimal
			Get
				Return _Freight
			End Get
			Set(ByVal value As Decimal)
				OnFreightChanging(value)
				ReportPropertyChanging("Freight")
				_Freight = StructuralObject.SetValidValue(value)
				ReportPropertyChanged("Freight")
				OnFreightChanged()
			End Set
		End Property
		Private _Freight As Global.System.Decimal
		Partial Private Sub OnFreightChanging(ByVal value As Global.System.Decimal)
		End Sub
		Partial Private Sub OnFreightChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=False), DataMemberAttribute()>
		Public Property TotalDue() As Global.System.Decimal
			Get
				Return _TotalDue
			End Get
			Set(ByVal value As Decimal)
				OnTotalDueChanging(value)
				ReportPropertyChanging("TotalDue")
				_TotalDue = StructuralObject.SetValidValue(value)
				ReportPropertyChanged("TotalDue")
				OnTotalDueChanged()
			End Set
		End Property
		Private _TotalDue As Global.System.Decimal
		Partial Private Sub OnTotalDueChanging(ByVal value As Global.System.Decimal)
		End Sub
		Partial Private Sub OnTotalDueChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True), DataMemberAttribute()>
		Public Property Comment() As Global.System.String
			Get
				Return _Comment
			End Get
			Set(ByVal value As String)
				OnCommentChanging(value)
				ReportPropertyChanging("Comment")
				_Comment = StructuralObject.SetValidValue(value, True)
				ReportPropertyChanged("Comment")
				OnCommentChanged()
			End Set
		End Property
		Private _Comment As Global.System.String
		Partial Private Sub OnCommentChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnCommentChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=False), DataMemberAttribute()>
		Public Property rowguid() As Global.System.Guid
			Get
				Return _rowguid
			End Get
			Set(ByVal value As Guid)
				OnrowguidChanging(value)
				ReportPropertyChanging("rowguid")
				_rowguid = StructuralObject.SetValidValue(value)
				ReportPropertyChanged("rowguid")
				OnrowguidChanged()
			End Set
		End Property
		Private _rowguid As Global.System.Guid
		Partial Private Sub OnrowguidChanging(ByVal value As Global.System.Guid)
		End Sub
		Partial Private Sub OnrowguidChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=False), DataMemberAttribute()>
		Public Property ModifiedDate() As Date
			Get
				Return _ModifiedDate
			End Get
			Set(ByVal value As Date)
				OnModifiedDateChanging(value)
				ReportPropertyChanging("ModifiedDate")
				_ModifiedDate = StructuralObject.SetValidValue(value)
				ReportPropertyChanged("ModifiedDate")
				OnModifiedDateChanged()
			End Set
		End Property
		Private _ModifiedDate As Date
		Partial Private Sub OnModifiedDateChanging(ByVal value As Date)
		End Sub
		Partial Private Sub OnModifiedDateChanged()
		End Sub

		#End Region

		#Region "Navigation Properties"

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<XmlIgnoreAttribute(), SoapIgnoreAttribute(), DataMemberAttribute(), EdmRelationshipNavigationPropertyAttribute("AdventureWorksLT_DataModel", "FK_SalesOrderHeader_Customer_CustomerID", "Customer")>
		Public Property Customer() As Customer
			Get
				Return (CType(Me, IEntityWithRelationships)).RelationshipManager.GetRelatedReference(Of Customer)("AdventureWorksLT_DataModel.FK_SalesOrderHeader_Customer_CustomerID", "Customer").Value
			End Get
			Set(ByVal value As Customer)
				CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Customer)("AdventureWorksLT_DataModel.FK_SalesOrderHeader_Customer_CustomerID", "Customer").Value = value
			End Set
		End Property
		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<BrowsableAttribute(False), DataMemberAttribute()>
		Public Property CustomerReference() As EntityReference(Of Customer)
			Get
				Return (CType(Me, IEntityWithRelationships)).RelationshipManager.GetRelatedReference(Of Customer)("AdventureWorksLT_DataModel.FK_SalesOrderHeader_Customer_CustomerID", "Customer")
			End Get
			Set(ByVal value As EntityReference(Of Customer))
				If (value IsNot Nothing) Then
					CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Customer)("AdventureWorksLT_DataModel.FK_SalesOrderHeader_Customer_CustomerID", "Customer", value)
				End If
			End Set
		End Property

		#End Region
	End Class

	#End Region

End Namespace
