<%@ Page Language="C#" AutoEventWireup="false" CodeFile="XmlDataSourceTreeView1.aspx.cs" Inherits="XmlDataSourceTreeView" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head runat="server">
    <title>Untitled Page</title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
     <asp:XmlDataSource ID="sourceDVD" runat="server" DataFile="~/DvdList.xml"></asp:XmlDataSource>
        <asp:TreeView ID="TreeView1" runat="server" DataSourceID="sourceDVD"
         AutoGenerateDataBindings="False">
    
                         <DataBindings>
             <asp:TreeNodeBinding DataMember="DvdList" Text="Root" Value="Root" />
           <asp:TreeNodeBinding DataMember="DVD" TextField="ID"  />
         <asp:TreeNodeBinding DataMember="Title" TextField="#InnerText" />
         </DataBindings>
      

        </asp:TreeView>
    </div>
    </form>
</body>
</html>
