' ----------------------------------------------------------------------------------
' Microsoft Developer & Platform Evangelism
' 
' Copyright (c) Microsoft Corporation. All rights reserved.
' 
' THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, 
' EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES 
' OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
' ----------------------------------------------------------------------------------
' The example companies, organizations, products, domain names,
' e-mail addresses, logos, people, places, and events depicted
' herein are fictitious.  No association with any real company,
' organization, product, domain name, email address, logo, person,
' places, or events is intended or should be inferred.
' ----------------------------------------------------------------------------------

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Collections.ObjectModel
Imports System.Collections.Specialized
Imports System.ComponentModel
Imports System.Globalization
Imports System.Runtime.Serialization
Imports System.Runtime.CompilerServices

<DataContract(IsReference:=False)>
<KnownType(GetType(CustomerAddress))>
<KnownType(GetType(SalesOrderHeader))>
Partial Public Class Address
    Implements IObjectWithChangeTracker
    Implements INotifyPropertyChanged

#Region "Primitive Properties"

    <DataMember()>
    Public Property AddressID() As Integer
        Get
            Return _addressID
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_addressID, value) Then
                If ChangeTracker.ChangeTrackingEnabled AndAlso ChangeTracker.State <> ObjectState.Added Then
                    Throw New InvalidOperationException("The property 'AddressID' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.")
                End If
                _addressID = value
                OnPropertyChanged("AddressID")
            End If
        End Set
    End Property

    Private _addressID As Integer

    <DataMember()>
    Public Property AddressLine1() As String
        Get
            Return _addressLine1
        End Get
        Set(ByVal value As String)
            If Not Equals(_addressLine1, value) Then
                _addressLine1 = value
                OnPropertyChanged("AddressLine1")
            End If
        End Set
    End Property

    Private _addressLine1 As String

    <DataMember()>
    Public Property AddressLine2() As String
        Get
            Return _addressLine2
        End Get
        Set(ByVal value As String)
            If Not Equals(_addressLine2, value) Then
                _addressLine2 = value
                OnPropertyChanged("AddressLine2")
            End If
        End Set
    End Property

    Private _addressLine2 As String

    <DataMember()>
    Public Property City() As String
        Get
            Return _city
        End Get
        Set(ByVal value As String)
            If Not Equals(_city, value) Then
                _city = value
                OnPropertyChanged("City")
            End If
        End Set
    End Property

    Private _city As String

    <DataMember()>
    Public Property StateProvince() As String
        Get
            Return _stateProvince
        End Get
        Set(ByVal value As String)
            If Not Equals(_stateProvince, value) Then
                _stateProvince = value
                OnPropertyChanged("StateProvince")
            End If
        End Set
    End Property

    Private _stateProvince As String

    <DataMember()>
    Public Property CountryRegion() As String
        Get
            Return _countryRegion
        End Get
        Set(ByVal value As String)
            If Not Equals(_countryRegion, value) Then
                _countryRegion = value
                OnPropertyChanged("CountryRegion")
            End If
        End Set
    End Property

    Private _countryRegion As String

    <DataMember()>
    Public Property PostalCode() As String
        Get
            Return _postalCode
        End Get
        Set(ByVal value As String)
            If Not Equals(_postalCode, value) Then
                _postalCode = value
                OnPropertyChanged("PostalCode")
            End If
        End Set
    End Property

    Private _postalCode As String

    <DataMember()>
    Public Property rowguid() As System.Guid
        Get
            Return _rowguid
        End Get
        Set(ByVal value As System.Guid)
            If Not Equals(_rowguid, value) Then
                _rowguid = value
                OnPropertyChanged("rowguid")
            End If
        End Set
    End Property

    Private _rowguid As System.Guid

    <DataMember()>
    Public Property ModifiedDate() As Date
        Get
            Return _modifiedDate
        End Get
        Set(ByVal value As Date)
            If Not Equals(_modifiedDate, value) Then
                _modifiedDate = value
                OnPropertyChanged("ModifiedDate")
            End If
        End Set
    End Property

    Private _modifiedDate As Date

#End Region
#Region "Navigation Properties"

    <DataMember()>
    Public Property CustomerAddresses() As TrackableCollection(Of CustomerAddress)
        Get
            If _customerAddresses Is Nothing Then
                _customerAddresses = New TrackableCollection(Of CustomerAddress)
                AddHandler _customerAddresses.CollectionChanged, AddressOf FixupCustomerAddresses
            End If
            Return _customerAddresses
        End Get
        Set(ByVal value As TrackableCollection(Of CustomerAddress))
            If Not Object.ReferenceEquals(_customerAddresses, value) Then
                If ChangeTracker.ChangeTrackingEnabled Then
                    Throw New InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled")
                End If
                If _customerAddresses IsNot Nothing Then
                    RemoveHandler _customerAddresses.CollectionChanged, AddressOf FixupCustomerAddresses
                    ' This is the principal end in an association that performs cascade deletes.
                    ' Remove the cascade delete event handler for any entities in the current collection.
                    For Each item As CustomerAddress In _customerAddresses
                        RemoveHandler ChangeTracker.ObjectStateChanging, AddressOf item.HandleCascadeDelete
                    Next
                End If
                _customerAddresses = value
                If _customerAddresses IsNot Nothing Then
                    AddHandler _customerAddresses.CollectionChanged, AddressOf FixupCustomerAddresses
                    ' This is the principal end in an association that performs cascade deletes.
                    ' Add the cascade delete event handler for any entities that are already in the new collection.
                    For Each item As CustomerAddress In _customerAddresses
                        AddHandler ChangeTracker.ObjectStateChanging, AddressOf item.HandleCascadeDelete
                    Next
                End If
                OnNavigationPropertyChanged("CustomerAddresses")
            End If
        End Set
    End Property

    Private _customerAddresses As TrackableCollection(Of CustomerAddress)

    <DataMember()>
    Public Property SalesOrderHeaders() As TrackableCollection(Of SalesOrderHeader)
        Get
            If _salesOrderHeaders Is Nothing Then
                _salesOrderHeaders = New TrackableCollection(Of SalesOrderHeader)
                AddHandler _salesOrderHeaders.CollectionChanged, AddressOf FixupSalesOrderHeaders
            End If
            Return _salesOrderHeaders
        End Get
        Set(ByVal value As TrackableCollection(Of SalesOrderHeader))
            If Not Object.ReferenceEquals(_salesOrderHeaders, value) Then
                If ChangeTracker.ChangeTrackingEnabled Then
                    Throw New InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled")
                End If
                If _salesOrderHeaders IsNot Nothing Then
                    RemoveHandler _salesOrderHeaders.CollectionChanged, AddressOf FixupSalesOrderHeaders
                End If
                _salesOrderHeaders = value
                If _salesOrderHeaders IsNot Nothing Then
                    AddHandler _salesOrderHeaders.CollectionChanged, AddressOf FixupSalesOrderHeaders
                End If
                OnNavigationPropertyChanged("SalesOrderHeaders")
            End If
        End Set
    End Property

    Private _salesOrderHeaders As TrackableCollection(Of SalesOrderHeader)

    <DataMember()>
    Public Property SalesOrderHeaders1() As TrackableCollection(Of SalesOrderHeader)
        Get
            If _salesOrderHeaders1 Is Nothing Then
                _salesOrderHeaders1 = New TrackableCollection(Of SalesOrderHeader)
                AddHandler _salesOrderHeaders1.CollectionChanged, AddressOf FixupSalesOrderHeaders1
            End If
            Return _salesOrderHeaders1
        End Get
        Set(ByVal value As TrackableCollection(Of SalesOrderHeader))
            If Not Object.ReferenceEquals(_salesOrderHeaders1, value) Then
                If ChangeTracker.ChangeTrackingEnabled Then
                    Throw New InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled")
                End If
                If _salesOrderHeaders1 IsNot Nothing Then
                    RemoveHandler _salesOrderHeaders1.CollectionChanged, AddressOf FixupSalesOrderHeaders1
                End If
                _salesOrderHeaders1 = value
                If _salesOrderHeaders1 IsNot Nothing Then
                    AddHandler _salesOrderHeaders1.CollectionChanged, AddressOf FixupSalesOrderHeaders1
                End If
                OnNavigationPropertyChanged("SalesOrderHeaders1")
            End If
        End Set
    End Property

    Private _salesOrderHeaders1 As TrackableCollection(Of SalesOrderHeader)

#End Region
#Region "ChangeTracking"

    Protected Overridable Sub OnPropertyChanged(ByVal propertyName As String)
        If ChangeTracker.State <> ObjectState.Added AndAlso ChangeTracker.State <> ObjectState.Deleted Then
            ChangeTracker.State = ObjectState.Modified
        End If
        RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
    End Sub

    Protected Overridable Sub OnNavigationPropertyChanged(ByVal propertyName As String)
        RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
    End Sub

    Private Event PropertyChanged As PropertyChangedEventHandler Implements INotifyPropertyChanged.PropertyChanged
    Private _changeTracker As ObjectChangeTracker

    <DataMember()>
    Public Property ChangeTracker() As ObjectChangeTracker Implements IObjectWithChangeTracker.ChangeTracker
        Get
            If _changeTracker Is Nothing Then
                _changeTracker = New ObjectChangeTracker()
                AddHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
            Return _changeTracker
        End Get
        Set(ByVal value As ObjectChangeTracker)
            If _changeTracker IsNot Nothing Then
                RemoveHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
            _changeTracker = value
            If _changeTracker IsNot Nothing Then
                AddHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
        End Set
    End Property

    Private Sub HandleObjectStateChanging(ByVal sender As Object, ByVal e As ObjectStateChangingEventArgs)
        If e.NewState = ObjectState.Deleted Then
            Me.ClearNavigationProperties()
        End If
    End Sub

    Private _isDeserializing As Boolean
    Protected Property IsDeserializing() As Boolean
        Get
            Return _isDeserializing
        End Get
        Private Set(ByVal value As Boolean)
            _isDeserializing = value
        End Set
    End Property

    <OnDeserializing()>
    Public Sub OnDeserializingMethod(ByVal context As StreamingContext)
        IsDeserializing = True
    End Sub

    <OnDeserialized()>
    Public Sub OnDeserializedMethod(ByVal context As StreamingContext)
        IsDeserializing = False
        ChangeTracker.ChangeTrackingEnabled = True
    End Sub

    Protected Overridable Sub ClearNavigationProperties()
        CustomerAddresses.Clear()
        SalesOrderHeaders.Clear()
        SalesOrderHeaders1.Clear()
    End Sub

#End Region
#Region "Association Fixup"

    Private Sub FixupCustomerAddresses(ByVal sender As Object, ByVal e As NotifyCollectionChangedEventArgs)
        If IsDeserializing Then
            Return
        End If

        If e.NewItems IsNot Nothing Then
            For Each item As CustomerAddress In e.NewItems
                item.Address = Me
                If ChangeTracker.ChangeTrackingEnabled Then
                    If Not item.ChangeTracker.ChangeTrackingEnabled Then
                        item.StartTracking()
                    End If
                    ChangeTracker.RecordAdditionToCollectionProperties("CustomerAddresses", item)
                End If
                ' This is the principal end in an association that performs cascade deletes.
                ' Update the event listener to refer to the new dependent.
                AddHandler ChangeTracker.ObjectStateChanging, AddressOf item.HandleCascadeDelete
            Next
        End If

        If e.OldItems IsNot Nothing Then
            For Each item As CustomerAddress In e.OldItems
                If ReferenceEquals(item.Address, Me) Then
                    item.Address = Nothing
                End If
                If ChangeTracker.ChangeTrackingEnabled Then
                    ChangeTracker.RecordRemovalFromCollectionProperties("CustomerAddresses", item)
                    ' Delete the dependent end of this identifying association. If the current state is Added,
                    ' allow the relationship to be changed without causing the dependent to be deleted.
                    If item.ChangeTracker.State <> ObjectState.Added Then
                        item.MarkAsDeleted()
                    End If
                End If
                ' This is the principal end in an association that performs cascade deletes.
                ' Remove the previous dependent from the event listener.
                RemoveHandler ChangeTracker.ObjectStateChanging, AddressOf item.HandleCascadeDelete
            Next
        End If
    End Sub

    Private Sub FixupSalesOrderHeaders(ByVal sender As Object, ByVal e As NotifyCollectionChangedEventArgs)
        If IsDeserializing Then
            Return
        End If

        If e.NewItems IsNot Nothing Then
            For Each item As SalesOrderHeader In e.NewItems
                item.Address = Me
                If ChangeTracker.ChangeTrackingEnabled Then
                    If Not item.ChangeTracker.ChangeTrackingEnabled Then
                        item.StartTracking()
                    End If
                    ChangeTracker.RecordAdditionToCollectionProperties("SalesOrderHeaders", item)
                End If
            Next
        End If

        If e.OldItems IsNot Nothing Then
            For Each item As SalesOrderHeader In e.OldItems
                If ReferenceEquals(item.Address, Me) Then
                    item.Address = Nothing
                End If
                If ChangeTracker.ChangeTrackingEnabled Then
                    ChangeTracker.RecordRemovalFromCollectionProperties("SalesOrderHeaders", item)
                End If
            Next
        End If
    End Sub

    Private Sub FixupSalesOrderHeaders1(ByVal sender As Object, ByVal e As NotifyCollectionChangedEventArgs)
        If IsDeserializing Then
            Return
        End If

        If e.NewItems IsNot Nothing Then
            For Each item As SalesOrderHeader In e.NewItems
                item.Address1 = Me
                If ChangeTracker.ChangeTrackingEnabled Then
                    If Not item.ChangeTracker.ChangeTrackingEnabled Then
                        item.StartTracking()
                    End If
                    ChangeTracker.RecordAdditionToCollectionProperties("SalesOrderHeaders1", item)
                End If
            Next
        End If

        If e.OldItems IsNot Nothing Then
            For Each item As SalesOrderHeader In e.OldItems
                If ReferenceEquals(item.Address1, Me) Then
                    item.Address1 = Nothing
                End If
                If ChangeTracker.ChangeTrackingEnabled Then
                    ChangeTracker.RecordRemovalFromCollectionProperties("SalesOrderHeaders1", item)
                End If
            Next
        End If
    End Sub

#End Region
End Class
