
#import "..\\UsefulManagedLibrary\\bin\\x86\\Debug\\UsefulManagedLibrary.tlb" no_namespace
//#import "..\\UsefulManagedLibrary\\bin\\x64\\Debug\\UsefulManagedLibrary.tlb" no_namespace

int main()
{
	CoInitialize(NULL);

	//Uses the UserNameDisplayer .NET class like any other COM objects, through
	//the type library generated by the registration process.
	{
		IUserNameDisplayerPtr ptr(__uuidof(UserNameDisplayer));
		ptr->DisplayUserName();
	}

	CoUninitialize();

	return 0;
}